layout_spectrum: 0.9444444
color:
  saturation: 0.6505376
  brandStrength: 0
  lightness: 0.7401434
  brandColors:
    - '#B2B6B3'
    - '#0D0D0C'
    - '#493A28'
    - '#415488'
    - '#B3B516'
  rhythmicContrast: 0.5663083
typography_spectrum: 0.7096774
name: Hojnicki Shah
